apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # Infrastructure hostnames (service names inside cluster)
  POSTGRES_HOST: "postgres"
  REDIS_HOST: "redis"
  KAFKA_BOOTSTRAP: "kafka:9092"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"

  # Common Spring config
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
  SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS: "10"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

  # Ports
  AUTH_SERVICE_URL: "http://auth-service:8089"
  USER_SERVICE_URL: "http://user-service:8081"
  PRODUCT_SERVICE_URL: "http://product-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8084"
  INVENTORY_SERVICE_URL: "http://inventory-service:8085"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8086"
  DELIVERY_SERVICE_URL: "http://delivery-service:8087"
  ML_SERVICE_URL: "http://ml-service:8090"
  AI_SERVICE_URL: "http://ai-service:8091"
  ACTION_ENGINE_URL: "http://action-engine:8092"
