apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce
type: Opaque
stringData:
  username: enter your username
  password: enter your password
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ecommerce
type: Opaque
stringData:
  secret: your-jwt-secret-key-change-in-production
