spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/order_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890AbcDef}

management:
  endpoints:
    web:
      exposure:
        include: health,info

